// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    using System;

    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<Type, int>(16)
            {
                { typeof(global::System.Collections.Generic.Dictionary<string, object>), 0 },
                { typeof(global::System.Collections.Generic.List<global::SyncPacketCollection.UnitData>), 1 },
                { typeof(global::System.Collections.Generic.List<ItemInfo>), 2 },
                { typeof(global::Common.ePacketType), 3 },
                { typeof(global::Common.PacketBase), 4 },
                { typeof(global::Common.PacketReward), 5 },
                { typeof(global::SyncPacketCollection.AttackDamage), 6 },
                { typeof(global::SyncPacketCollection.GameResult), 7 },
                { typeof(global::SyncPacketCollection.PlayerInfo), 8 },
                { typeof(global::SyncPacketCollection.Ready), 9 },
                { typeof(global::SyncPacketCollection.SVector3), 10 },
                { typeof(global::SyncPacketCollection.SyncPacketBase), 11 },
                { typeof(global::SyncPacketCollection.UnitData), 12 },
                { typeof(global::SyncPacketCollection.UpdateAttackCombo), 13 },
                { typeof(global::SyncPacketCollection.UpdateStackDamage), 14 },
                { typeof(global::SyncPacketCollection.UpdateUnit), 15 },
            };
        }

        internal static object GetFormatter(Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.DictionaryFormatter<string, object>();
                case 1: return new global::MessagePack.Formatters.ListFormatter<global::SyncPacketCollection.UnitData>();
                case 2: return new global::MessagePack.Formatters.ListFormatter<ItemInfo>();
                case 3: return new MessagePack.Formatters.Common.ePacketTypeFormatter();
                case 4: return new MessagePack.Formatters.Common.PacketBaseFormatter();
                case 5: return new MessagePack.Formatters.Common.PacketRewardFormatter();
                case 6: return new MessagePack.Formatters.SyncPacketCollection.AttackDamageFormatter();
                case 7: return new MessagePack.Formatters.SyncPacketCollection.GameResultFormatter();
                case 8: return new MessagePack.Formatters.SyncPacketCollection.PlayerInfoFormatter();
                case 9: return new MessagePack.Formatters.SyncPacketCollection.ReadyFormatter();
                case 10: return new MessagePack.Formatters.SyncPacketCollection.SVector3Formatter();
                case 11: return new MessagePack.Formatters.SyncPacketCollection.SyncPacketBaseFormatter();
                case 12: return new MessagePack.Formatters.SyncPacketCollection.UnitDataFormatter();
                case 13: return new MessagePack.Formatters.SyncPacketCollection.UpdateAttackComboFormatter();
                case 14: return new MessagePack.Formatters.SyncPacketCollection.UpdateStackDamageFormatter();
                case 15: return new MessagePack.Formatters.SyncPacketCollection.UpdateUnitFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1649 // File name should match first type name


// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Common
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class ePacketTypeFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Common.ePacketType>
    {
        public void Serialize(ref MessagePackWriter writer, global::Common.ePacketType value, global::MessagePack.MessagePackSerializerOptions options)
        {
            writer.Write((Int32)value);
        }

        public global::Common.ePacketType Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            return (global::Common.ePacketType)reader.ReadInt32();
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name



// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Common
{
    using global::System.Buffers;
    using global::MessagePack;

    public sealed class PacketBaseFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Common.PacketBase>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Common.PacketBase value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(2);
            formatterResolver.GetFormatterWithVerify<global::Common.ePacketType>().Serialize(ref writer, value.PacketType, options);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<string, object>>().Serialize(ref writer, value.hash, options);
        }

        public global::Common.PacketBase Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Common.PacketBase();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.PacketType = formatterResolver.GetFormatterWithVerify<global::Common.ePacketType>().Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.hash = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<string, object>>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class PacketRewardFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Common.PacketReward>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Common.PacketReward value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(3);
            formatterResolver.GetFormatterWithVerify<global::Common.ePacketType>().Serialize(ref writer, value.PacketType, options);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<string, object>>().Serialize(ref writer, value.hash, options);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<ItemInfo>>().Serialize(ref writer, value.Rewards, options);
        }

        public global::Common.PacketReward Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Common.PacketReward();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.PacketType = formatterResolver.GetFormatterWithVerify<global::Common.ePacketType>().Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.hash = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<string, object>>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.Rewards = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<ItemInfo>>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.SyncPacketCollection
{
    using global::System.Buffers;
    using global::MessagePack;

    public sealed class AttackDamageFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SyncPacketCollection.AttackDamage>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SyncPacketCollection.AttackDamage value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            writer.WriteArrayHeader(2);
            writer.Write(value.PacketType);
            writer.Write(value.Damage);
        }

        public global::SyncPacketCollection.AttackDamage Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadArrayHeader();
            var ____result = new global::SyncPacketCollection.AttackDamage();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.PacketType = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.Damage = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class GameResultFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SyncPacketCollection.GameResult>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SyncPacketCollection.GameResult value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(3);
            writer.Write(value.PacketType);
            formatterResolver.GetFormatterWithVerify<global::System.DateTime>().Serialize(ref writer, value.GameOverTime, options);
            writer.Write(value.isGameOver);
        }

        public global::SyncPacketCollection.GameResult Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SyncPacketCollection.GameResult();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.PacketType = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.GameOverTime = formatterResolver.GetFormatterWithVerify<global::System.DateTime>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.isGameOver = reader.ReadBoolean();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class PlayerInfoFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SyncPacketCollection.PlayerInfo>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SyncPacketCollection.PlayerInfo value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(4);
            writer.Write(value.PacketType);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.HeroKey, options);
            writer.Write(value.MMR);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Name, options);
        }

        public global::SyncPacketCollection.PlayerInfo Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SyncPacketCollection.PlayerInfo();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.PacketType = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.HeroKey = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.MMR = reader.ReadInt32();
                        break;
                    case 3:
                        ____result.Name = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class ReadyFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SyncPacketCollection.Ready>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SyncPacketCollection.Ready value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(2);
            writer.Write(value.PacketType);
            formatterResolver.GetFormatterWithVerify<global::System.DateTime>().Serialize(ref writer, value.ReadyTime, options);
        }

        public global::SyncPacketCollection.Ready Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SyncPacketCollection.Ready();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.PacketType = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.ReadyTime = formatterResolver.GetFormatterWithVerify<global::System.DateTime>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class SVector3Formatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SyncPacketCollection.SVector3>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SyncPacketCollection.SVector3 value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            writer.WriteArrayHeader(3);
            writer.Write(value.x);
            writer.Write(value.y);
            writer.Write(value.z);
        }

        public global::SyncPacketCollection.SVector3 Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadArrayHeader();
            var ____result = new global::SyncPacketCollection.SVector3();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.x = reader.ReadInt16();
                        break;
                    case 1:
                        ____result.y = reader.ReadInt16();
                        break;
                    case 2:
                        ____result.z = reader.ReadInt16();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class SyncPacketBaseFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SyncPacketCollection.SyncPacketBase>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SyncPacketCollection.SyncPacketBase value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            writer.WriteArrayHeader(1);
            writer.Write(value.PacketType);
        }

        public global::SyncPacketCollection.SyncPacketBase Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadArrayHeader();
            var ____result = new global::SyncPacketCollection.SyncPacketBase();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.PacketType = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class UnitDataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SyncPacketCollection.UnitData>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SyncPacketCollection.UnitData value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(3);
            writer.Write(value.UnitKey);
            formatterResolver.GetFormatterWithVerify<global::SyncPacketCollection.SVector3>().Serialize(ref writer, value.UnitPosition, options);
            formatterResolver.GetFormatterWithVerify<global::SyncPacketCollection.SVector3>().Serialize(ref writer, value.UnitRotation, options);
        }

        public global::SyncPacketCollection.UnitData Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SyncPacketCollection.UnitData();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.UnitKey = reader.ReadSByte();
                        break;
                    case 1:
                        ____result.UnitPosition = formatterResolver.GetFormatterWithVerify<global::SyncPacketCollection.SVector3>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.UnitRotation = formatterResolver.GetFormatterWithVerify<global::SyncPacketCollection.SVector3>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class UpdateAttackComboFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SyncPacketCollection.UpdateAttackCombo>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SyncPacketCollection.UpdateAttackCombo value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            writer.WriteArrayHeader(2);
            writer.Write(value.PacketType);
            writer.Write(value.Combo);
        }

        public global::SyncPacketCollection.UpdateAttackCombo Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadArrayHeader();
            var ____result = new global::SyncPacketCollection.UpdateAttackCombo();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.PacketType = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.Combo = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class UpdateStackDamageFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SyncPacketCollection.UpdateStackDamage>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SyncPacketCollection.UpdateStackDamage value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            writer.WriteArrayHeader(2);
            writer.Write(value.PacketType);
            writer.Write(value.StackDamage);
        }

        public global::SyncPacketCollection.UpdateStackDamage Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadArrayHeader();
            var ____result = new global::SyncPacketCollection.UpdateStackDamage();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.PacketType = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.StackDamage = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class UpdateUnitFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SyncPacketCollection.UpdateUnit>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SyncPacketCollection.UpdateUnit value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(2);
            writer.Write(value.PacketType);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<global::SyncPacketCollection.UnitData>>().Serialize(ref writer, value.UnitDatas, options);
        }

        public global::SyncPacketCollection.UpdateUnit Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SyncPacketCollection.UpdateUnit();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.PacketType = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.UnitDatas = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<global::SyncPacketCollection.UnitData>>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

